### ISSUE TITLE
微前端子应用报错

### ISSUE THREAD

**Issue by TigerBill2016** [web-infra-dev/modern-js-examples#21]
![image](https://user-images.githubusercontent.com/19324557/153366823-cdc3c4e6-4017-4d2e-adff-473a81495eb9.png)

npm run dev 没有报错，访问页面有报错，请问这是什么问题造成的。

**Comment by chenjiahan** [comment]
由于这个 issue 已经不再活跃，我将关闭它。

如果此问题还存在，请到 modern.js 仓库反馈：https://github.com/web-infra-dev/modern.js
